import type { LevelDef } from './types';

/** The standard six pockets, for levels that start from the plain table. */
const RECT = (): LevelDef['shape'] => [
  { x: 0, y: 0, pocket: true },
  { x: 500, y: 0, pocket: true },
  { x: 1000, y: 0, pocket: true },
  { x: 1000, y: 500, pocket: true },
  { x: 500, y: 500, pocket: true },
  { x: 0, y: 500, pocket: true },
];

/**
 * The Rec Room: twelve tables, each built around one or two mechanics. Every level has a recorded
 * solution (tests/levels/solutions) that CI plays through the real game.
 */
export const REC_ROOM: readonly LevelDef[] = [
  {
    id: 'rr-01',
    n: 1,
    name: 'BEND HERE',
    blurb: "The cue only goes where it goes. So move the pocket to where the ball's going.",
    teaches: 'BENDING',
    shape: RECT(),
    balls: [
      { num: 0, x: 250, y: 250 },
      { num: 1, x: 600, y: 250 },
    ],
    angles: [0],
    shots: 1,
    tokens: 2,
    reach: 280,
    english: false,
    goal: { kind: 'clearAll' },
    stars: { three: { tokens: 1 }, two: { tokens: 2 } },
    hint: 'Grab the top-right knob and pull the pocket down into the ball’s path.',
  },
  {
    id: 'rr-02',
    n: 2,
    name: 'BOLTED DOWN',
    blurb: 'Every corner is bolted to the floor. The rails between them, though... those still bend.',
    teaches: 'BOLTS & NEW BENDS',
    shape: [
      { x: 0, y: 0, pocket: true, bolted: true },
      { x: 500, y: 0, pocket: true },
      { x: 1000, y: 0, pocket: true, bolted: true },
      { x: 1000, y: 500, pocket: true, bolted: true },
      { x: 500, y: 500, pocket: true },
      { x: 0, y: 500, pocket: true, bolted: true },
    ],
    balls: [
      { num: 0, x: 420, y: 250 },
      { num: 2, x: 700, y: 250 },
      { num: 6, x: 180, y: 250 },
    ],
    angles: [0, 180],
    shots: 2,
    tokens: 3,
    reach: 220,
    english: false,
    goal: { kind: 'clearAll' },
    stars: { three: { tokens: 2 }, two: { tokens: 3 } },
    hint: 'Grab the ＋ in the middle of a rail to add a bend, then pull it to angle the rail.',
  },
  {
    id: 'rr-03',
    n: 3,
    name: 'BOING BOING',
    blurb: 'Bouncy rails, three bumpers that hit back, and one job: bank a ball in off two cushions.',
    teaches: 'BUMPERS & BOUNCY RAILS',
    shape: [
      { x: 0, y: 0, pocket: true, mat: 'trampoline' },
      { x: 500, y: 0, pocket: true, mat: 'trampoline' },
      { x: 1000, y: 0, pocket: true },
      { x: 1000, y: 500, pocket: true, mat: 'trampoline' },
      { x: 500, y: 500, pocket: true, mat: 'trampoline' },
      { x: 0, y: 500, pocket: true },
    ],
    balls: [
      { num: 0, x: 160, y: 250 },
      { num: 3, x: 760, y: 250 },
    ],
    parts: [
      { id: 101, kind: 'bumper', x: 420, y: 250, r: 30, locked: true },
      { id: 102, kind: 'bumper', x: 600, y: 140, r: 30, locked: true },
      { id: 103, kind: 'bumper', x: 600, y: 360, r: 30, locked: true },
    ],
    angles: [20, 200],
    shots: 2,
    tokens: 2,
    reach: 200,
    english: false,
    goal: { kind: 'bank', cushions: 2 },
    stars: { three: { score: 1, tokens: 1 }, two: { score: 1 } },
    hint: 'Watch the guide bounce. A small bend near where it lands goes a long way.',
  },
  {
    id: 'rr-04',
    n: 4,
    name: 'ZOOM LANE',
    blurb: 'A long, skinny hallway with steel walls. Put the speed pad where it will do the most good.',
    teaches: 'BOOSTERS',
    shape: [
      { x: -80, y: 140, pocket: true, bolted: true, mat: 'steel' },
      { x: 500, y: 140, pocket: true, mat: 'steel' },
      { x: 1080, y: 140, pocket: true },
      { x: 1080, y: 360, pocket: true, mat: 'steel' },
      { x: 500, y: 360, pocket: true, mat: 'steel' },
      { x: -80, y: 360, pocket: true, bolted: true },
    ],
    balls: [
      { num: 0, x: 20, y: 250 },
      { num: 3, x: 640, y: 200 },
      { num: 7, x: 780, y: 300 },
      { num: 5, x: 960, y: 210 },
    ],
    tray: [{ preset: { kind: 'booster', dir: { x: 1000, y: 0 }, len: 120, wid: 70, kick: 700 }, count: 1 }],
    angles: [12, 348],
    shots: 2,
    tokens: 2,
    reach: 250,
    english: false,
    goal: { kind: 'sink', ball: 5 },
    stars: { three: { score: 1 }, two: { tokens: 1 } },
    hint: 'Drag the speed pad out of the box onto the table. Arrows show which way it kicks.',
  },
  {
    id: 'rr-05',
    n: 5,
    name: "SLIP 'N SLIDE",
    blurb: 'Ice keeps a ball going. The belt carries it along. Somewhere in there is a nice spot to stop.',
    teaches: 'ICE & CONVEYOR BELTS',
    shape: RECT(),
    balls: [
      { num: 0, x: 120, y: 110 },
      { num: 8, x: 520, y: 320 },
    ],
    parts: [
      {
        id: 101,
        kind: 'felt',
        felt: 'ice',
        x: 400,
        y: 250,
        dir: { x: 1000, y: 0 },
        w: 440,
        h: 300,
        locked: true,
      },
      {
        id: 102,
        kind: 'felt',
        felt: 'conveyor',
        x: 720,
        y: 250,
        dir: { x: 0, y: 1000 },
        w: 420,
        h: 90,
        locked: true,
      },
      { id: 103, kind: 'bullseye', x: 860, y: 380, r: 44, locked: true },
    ],
    tray: [{ preset: { kind: 'felt', felt: 'mud', dir: { x: 1000, y: 0 }, w: 180, h: 120 }, count: 1 }],
    angles: [20, 200, 300],
    shots: 3,
    tokens: 3,
    reach: 200,
    english: false,
    goal: { kind: 'park', bullseye: 103 },
    stars: { three: { score: 1 }, two: { score: 2 } },
    hint: 'Mud stops a ball fast. A patch of it next to the target makes a good brake.',
  },
  {
    id: 'rr-06',
    n: 6,
    name: 'PORTAL PARTY',
    blurb: 'A wall down the middle with a one-way gate. Or you could just go through the portal.',
    teaches: 'PORTALS & GATES',
    shape: [
      { x: 0, y: 0, pocket: true },
      { x: 500, y: 0, pocket: false },
      { x: 1000, y: 0, pocket: true },
      { x: 1000, y: 500, pocket: true },
      { x: 500, y: 500, pocket: false },
      { x: 0, y: 500, pocket: true },
    ],
    balls: [
      { num: 0, x: 130, y: 250 },
      { num: 4, x: 300, y: 330 },
      { num: 1, x: 820, y: 150 },
      { num: 2, x: 880, y: 320 },
    ],
    parts: [
      { id: 101, kind: 'stub', x: 500, y: 105, dir: { x: 0, y: 1000 }, len: 130, locked: true },
      { id: 102, kind: 'stub', x: 500, y: 395, dir: { x: 0, y: 1000 }, len: 130, locked: true },
      { id: 103, kind: 'gate', x: 500, y: 250, dir: { x: 1000, y: 0 }, len: 80, locked: true },
      { id: 104, kind: 'portal', x: 250, y: 110, link: 105, r: 38, locked: true },
      { id: 105, kind: 'portal', x: 760, y: 400, link: 104, r: 38 },
    ],
    angles: [45, 135, 315],
    shots: 3,
    tokens: 2,
    reach: 200,
    english: false,
    goal: { kind: 'combo', n: 2 },
    stars: { three: { score: 1 }, two: { score: 2 } },
    hint: 'One portal is bolted down, the other can be moved. A ball that rolls into one comes out of the other, same speed, same way.',
  },
  {
    id: 'rr-07',
    n: 7,
    name: 'PICKY EATERS',
    blurb:
      'Warm pockets only eat warm balls (odd numbers). Cool pockets only eat cool ones. The middle two are corked for now.',
    teaches: 'PICKY & CORKED POCKETS',
    shape: [
      { x: 0, y: 0, pocket: true, trait: { kind: 'picky', suit: 'warm' } },
      { x: 500, y: 0, pocket: true, trait: { kind: 'corked', strokes: 2 } },
      { x: 1000, y: 0, pocket: true, trait: { kind: 'picky', suit: 'cool' } },
      { x: 1000, y: 500, pocket: true, trait: { kind: 'picky', suit: 'warm' } },
      { x: 500, y: 500, pocket: true, trait: { kind: 'corked', strokes: 2 } },
      { x: 0, y: 500, pocket: true, trait: { kind: 'picky', suit: 'cool' } },
    ],
    balls: [
      { num: 0, x: 200, y: 250 },
      { num: 3, x: 640, y: 140 },
      { num: 5, x: 700, y: 360 },
      { num: 2, x: 380, y: 360 },
    ],
    angles: [10, 190, 80, 260, 350],
    shots: 5,
    tokens: 4,
    reach: 220,
    english: false,
    goal: { kind: 'clearAll' },
    stars: { three: { score: 3 }, two: { score: 4 } },
    hint: 'A pocket that will not eat a ball spits it straight back out. Steer each ball to a pocket of its colour.',
  },
  {
    id: 'rr-08',
    n: 8,
    name: 'SCREWBALL',
    blurb:
      'No grabs at all this time. Drag the dot on the little cue ball: low makes it screw back, high makes it follow through.',
    teaches: 'ENGLISH',
    shape: [
      { x: 0, y: 0, pocket: true },
      { x: 500, y: 0, pocket: true },
      { x: 1000, y: 0, pocket: true },
      { x: 1000, y: 150, pocket: true },
      { x: 1000, y: 500, pocket: true },
      { x: 500, y: 500, pocket: true },
      { x: 0, y: 500, pocket: true },
      { x: 0, y: 150, pocket: true },
    ],
    balls: [
      { num: 0, x: 260, y: 150 },
      { num: 1, x: 420, y: 150 },
      { num: 2, x: 130, y: 150 },
    ],
    angles: [0, 172],
    shots: 2,
    tokens: 0,
    reach: 200,
    english: true,
    goal: { kind: 'clearAll' },
    stars: { three: { score: 1 }, two: { score: 2 } },
    hint: 'Pull the dot right down to the bottom and hit hard: the cue ball sinks the 1, then screws back for the 2.',
  },
  {
    id: 'rr-09',
    n: 9,
    name: 'CHOMP CHOMP',
    blurb:
      'For once, sink the cue ball on purpose: into one of the chompers on the right. They only open now and then.',
    teaches: 'CHOMPERS & GENTLE POCKETS',
    shape: [
      { x: 0, y: 0, pocket: true, trait: { kind: 'gentle', vmax: 300 } },
      { x: 500, y: 0, pocket: true, trait: { kind: 'gentle', vmax: 300 } },
      { x: 1000, y: 0, pocket: true, trait: { kind: 'chomper', period: 1.6, open: 0.45, phase: 0 } },
      { x: 1000, y: 500, pocket: true, trait: { kind: 'chomper', period: 1.6, open: 0.45, phase: 0.8 } },
      { x: 500, y: 500, pocket: true, trait: { kind: 'gentle', vmax: 300 } },
      { x: 0, y: 500, pocket: true, trait: { kind: 'gentle', vmax: 300 } },
    ],
    balls: [
      { num: 0, x: 180, y: 250 },
      { num: 4, x: 640, y: 190 },
      { num: 6, x: 640, y: 320 },
    ],
    angles: [25, 335, 30],
    shots: 3,
    tokens: 3,
    reach: 200,
    english: true,
    goal: { kind: 'scratch', pockets: [2, 3] },
    stars: { three: { score: 1 }, two: { score: 2 } },
    hint: 'Watch the jaws: the dial round each one shows when it opens. Power changes when you get there.',
  },
  {
    id: 'rr-10',
    n: 10,
    name: 'WHICH CAME FIRST?',
    blurb:
      'Sink the egg, then the chicken. Hit the egg too hard and it breaks; get close to the chicken and it runs.',
    teaches: 'EGGS & CHICKENS',
    shape: [
      { x: 0, y: 0, pocket: true },
      { x: 600, y: 0, pocket: true },
      { x: 600, y: 220, pocket: false },
      { x: 1000, y: 220, pocket: true },
      { x: 1000, y: 500, pocket: true },
      { x: 500, y: 500, pocket: true },
      { x: 0, y: 500, pocket: true },
    ],
    balls: [
      { num: 0, x: 120, y: 400 },
      { num: 3, x: 300, y: 200, variant: 'egg' },
      { num: 5, x: 820, y: 380, variant: 'chicken' },
    ],
    tray: [
      { preset: { kind: 'arc', r: 110, from: { x: 1000, y: 0 }, to: { x: 0, y: 1000 } }, count: 1 },
      { preset: { kind: 'stub', dir: { x: 1000, y: 0 }, len: 140 }, count: 2 },
    ],
    angles: [340, 20, 60, 200],
    shots: 4,
    tokens: 4,
    reach: 220,
    english: true,
    goal: { kind: 'order', balls: [3, 5] },
    stars: { three: { score: 2 }, two: { score: 3 } },
    hint: 'Gentle with the egg. Then corner the chicken: walls from the box can block its escape.',
  },
  {
    id: 'rr-11',
    n: 11,
    name: 'HEAVY METAL',
    blurb: 'A bowling ball, a bomb and two panes of glass. Clear everything except the golden 1.',
    teaches: 'HEAVY BALLS, BOMBS & GLASS',
    shape: [
      { x: 0, y: 0, pocket: true, mat: 'steel' },
      { x: 500, y: 0, pocket: true, mat: 'steel' },
      { x: 1000, y: 0, pocket: true },
      { x: 1000, y: 500, pocket: true, mat: 'steel' },
      { x: 500, y: 500, pocket: true, mat: 'steel' },
      { x: 0, y: 500, pocket: true },
    ],
    balls: [
      { num: 0, x: 150, y: 250 },
      { num: 8, x: 400, y: 250, variant: 'bowling' },
      { num: 5, x: 720, y: 160, variant: 'bomb' },
      { num: 1, x: 820, y: 340, variant: 'golden' },
      { num: 3, x: 620, y: 390 },
    ],
    parts: [
      { id: 101, kind: 'glass', x: 900, y: 100, dir: { x: 1000, y: 1000 }, len: 110, hp: 2, locked: true },
      { id: 102, kind: 'glass', x: 500, y: 420, dir: { x: 1000, y: 0 }, len: 120, hp: 2, locked: true },
    ],
    angles: [0, 30, 330, 200],
    shots: 4,
    tokens: 3,
    reach: 220,
    english: true,
    goal: { kind: 'spare', ball: 1 },
    stars: { three: { score: 2 }, two: { score: 3 } },
    hint: 'The bomb goes off on its third hard knock and takes everything near it along. Keep the golden 1 well away.',
  },
  {
    id: 'rr-12',
    n: 12,
    name: 'THE BLACK HOLE',
    blurb:
      'Everything that falls in comes back out somewhere else. A magnet pulls, a repulsor pushes. Good luck.',
    teaches: 'BLACK HOLES & MAGNETS',
    shape: [
      { x: 0, y: 0, pocket: true },
      { x: 500, y: -60, pocket: true },
      { x: 1000, y: 0, pocket: true },
      { x: 1060, y: 250, pocket: false },
      { x: 1000, y: 500, pocket: true },
      { x: 500, y: 560, pocket: true },
      { x: 0, y: 500, pocket: true },
      { x: -60, y: 250, pocket: false },
    ],
    balls: [
      { num: 0, x: 110, y: 250 },
      { num: 2, x: 330, y: 160 },
      { num: 3, x: 690, y: 420 },
      { num: 6, x: 870, y: 250 },
      { num: 7, x: 390, y: 430 },
    ],
    parts: [
      {
        id: 101,
        kind: 'blackhole',
        x: 500,
        y: 250,
        r: 110,
        exits: [
          { x: 500, y: 90 },
          { x: 500, y: 410 },
          { x: 330, y: 250 },
          { x: 670, y: 250 },
        ],
        locked: true,
      },
      { id: 102, kind: 'magnet', x: 790, y: 110, polarity: 1, r: 130, strength: 1100, locked: true },
      { id: 103, kind: 'magnet', x: 210, y: 400, polarity: -1, r: 110, strength: 1000, locked: true },
      { id: 104, kind: 'bumper', x: 690, y: 320, r: 28, locked: true },
    ],
    angles: [0, 120, 240, 60],
    shots: 4,
    tokens: 4,
    reach: 250,
    english: true,
    goal: { kind: 'clearAll' },
    stars: { three: { score: 2 }, two: { score: 3 } },
    hint: 'Balls come out of the black hole at one of the four little rings, picked at random. Plan around all four.',
  },
];

export function levelById(id: string): LevelDef | undefined {
  return REC_ROOM.find((l) => l.id === id);
}
